version: '3.1'
services:
  newrelic-infra:
    image: newrelic/infrastructure:latest
    hostname: newrelic-infra
    container_name: newrelic-infra
    environment:
      NRIA_IS_FORWARD_ONLY: true
      NRIA_K8S_INTEGRATION: true
      NRIA_LOG_LEVEL: info
      NRIA_LICENSE_KEY: your_key
    volumes:
      - ./newrelic-infra/integrations:/etc/newrelic-infra/integrations.d
      - /var/run/docker.sock:/var/run/docker.sock